services:
  espy:
    image: ruby:3.3.4-slim-bookworm
    container_name: espy-dev
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '../grenander:/grenander'
    working_dir: /app
    environment:
      - GRENANDER_PATH=/grenander
    command: >
      bash -c "apt update &&
              apt install -y build-essential apt-utils git nodejs &&
              cd /app &&
              mkdir -p tmp/pids &&
              rm -f tmp/pids/server.pid &&
              bundle install &&
              bundle exec rails db:migrate &&
              bundle exec rails server -b 0.0.0.0"